# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: admin
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 0cc786b3701c2a29b4a874d86b69e9b7f4175632f49ce264e59fd3e197a89450a610161e6ef8e20bdb6e1c916ecd2176ef0fd92d0d2bb21fad0ffdd480664796

test:
  secret_key_base: very_long_random_string
  domain_name: example.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: admin
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
